name: Build
'on':
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
           3.1.x
           5.0.x
      - name: Build and analyze
        env:
          GITHUB_TOKEN: 85f69b06-5f11-4e2a-aa13-2de281ba6fdb
          SONAR_TOKEN: 6c6b2469c3347bcc5a90cd7dbec5c8ce8a816eb6
        run: >-
         dotnet run -- --patate 1 --active true
         dotnet tool install --global dotnet-sonarscanner
         dotnet sonarscanner begin /k:"examly-test_85f69b06-5f11-4e2a-aa13-2de281ba6fdb" /o:"examly-test" /d:sonar.login="6c6b2469c3347bcc5a90cd7dbec5c8ce8a816eb6"
         dotnet build mvc-angularjs/src/EventCloud.sln
         dotnet sonarscanner end /d:sonar.login="6c6b2469c3347bcc5a90cd7dbec5c8ce8a816eb6"
